export let data = [];
async function fetchData() {
  try {
      const response = await fetch('http://127.0.0.1:5000/api/data');
      if (!response.ok) throw new Error('Failed to fetch data');
      data = await response.json();
  } catch (error) {
    console.error('Error fetching data:', error);
  }
}

// export const data = [
//   {
//     id: "PID-8921",
//     name: "Rahul Sharma",
//     avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCMUdfbuUcHQxO_oISwgnIxjkYHJyClDEum_2ZGJyyoO3eUnQQJPLzfySuoSuCb03FG6Zz8SV8qBf5PlUhZlgc-7llBZRJ5FQs6_uATq0qlhaN-6Fi2VEW5Rl-liocvHUxLP63YmxYyBf7fyAQJlXz6e9s8nUQYLcSZE6aasugnSFW1cKx15H0Rh26FZWPX24YwRqh43Vy0YjRlP6Y2JPhmMDbYkeX4iYQAEtcZuM0DtnCfv2apkgqdXN44arth-4gBLSxZnIGJcl4",
//     department: "Innovation Labs",
//     role: "Product Manager",
//     jobLevel: "Manager",
//     orgUnit: "Innovation & Strategy",
//     division: "Consumer",
//     doj: "2018-06-12",
//     location: "Mumbai",
//     assessment: "Done",
//     projectScore: 88,
//     perfRating: 4.5,
//     oaapScore: 92,
//     technicalAssessmentScore: 85,
//     cognitiveAptitudeScore: 89,
//     recentProjectRating: 4.2,
//     deliverySpeed: 4.0,
//     employmentType: "Full-Time Permanent",
//     currentCompensationBand: "Band L3-B",
//     adjustedOaapScore: 9.2,
//     key: true,
//     potential: "High",
//     readiness: "Ready Now",
//     readinessPct: 100,
//     tag: "Top Performer",
//   },
//   {
//     id: "PID-3342",
//     name: "Anita Desai",
//     avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuB4kt2o9M-YOnGNXm4RTeNzMIC3196HKKfOX--tcmkLh9tgIsj-vNTxY3NmIQsrKc6fWg7mJlGRZgAwNFup3H4wT5dHXsspJALodNlTKIxNlDAQnVAnkWRHX1vYEd0qXmzNNhKcOVSxlKAroXO5Ka68Cq1BpAAk7ZUtMLfEdyXbph_AMbLlZ_y3XCAZCAC5Lzth3EBNLKSiUv3joR0ysym_1hmy6RMH5WtZKrzG8sb_76NYi6l3EW6l0CyWCdX8r_L_62hIkGhcI14",
//     department: "Sales & Marketing",
//     role: "Regional Head",
//     jobLevel: "Executive",
//     orgUnit: "Commercial - West",
//     division: "Commercial",
//     doj: "2017-03-25",
//     location: "Bangalore",
//     assessment: "Done",
//     projectScore: 95,
//     perfRating: 4.9,
//     oaapScore: 96,
//     technicalAssessmentScore: 90,
//     cognitiveAptitudeScore: 93,
//     recentProjectRating: 4.7,
//     deliverySpeed: 4.8,
//     employmentType: "Full-Time Permanent",
//     currentCompensationBand: "Band L4-A",
//     adjustedOaapScore: 9.7,
//     key: true,
//     potential: "High",
//     readiness: "Ready Now",
//     readinessPct: 100,
//     tag: "Top Performer",
//   },
//   {
//     id: "PID-1029",
//     name: "Vikram Singh",
//     avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuCL-mmDeEtUp3pjadoHUuTWh5ZOOmygEBYgwv5JgtrZE5rh1k8HtLPv5VLOAjbMyNlr1_mTNXqG6nzdO_ihVLcBQ6uPFxWCfNgkzZOv4JhzyTpJvBNsmwc-JkfL3qFnm0_4lCG-qsfuO3uLKUnE_my9CaA1jHAIr1FS9SsMq1zPqtHI-MhuEhUN24dVl84fdPjwyJNgIUEk_EGgYPgug9aNgRvTYA-Zma4Kh0n0d2qrkaX6q_p1_NA-Nw6q8ctSjPmudTrv2KlJ1YY",
//     department: "Operations",
//     role: "Plant Supervisor",
//     jobLevel: "Mid-level",
//     orgUnit: "Operations - Plant A",
//     division: "Industrial",
//     doj: "2019-11-05",
//     location: "Pune",
//     assessment: "Pending",
//     projectScore: 72,
//     perfRating: 3.8,
//     oaapScore: 78,
//     technicalAssessmentScore: 70,
//     cognitiveAptitudeScore: 75,
//     recentProjectRating: 3.5,
//     deliverySpeed: 3.8,
//     employmentType: "Full-Time Permanent",
//     currentCompensationBand: "Band L2-C",
//     adjustedOaapScore: 7.5,
//     key: false,
//     potential: "Medium",
//     readiness: "Ready Now",
//     readinessPct: 100,
//     tag: "Flight Risk",
//   },
//   {
//     id: "PID-5501",
//     name: "Sarah Jenkins",
//     avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAH7jAvO80V3dXR764f9gJn4ljINmIfaw05IxW_nwAjph_8AyHgf7Zt94R_notYLy4lfNwHm0B7bbCgNLpVkCH02Z0Ly8Iw5dntuuNE4DFOOIFn4wLysI0kVOfuHp0intJOxOA-1fQAd7IQ1bPXOy9qd1cNedJjYFl10ZbDYSqrooLabMAuWRMPcp63NWAk6pr-3015XfqzF3rNPjItxc8YGLzOOhOsKHAbyXINz5c8K6WB_jKq2-6VhWJ1579x-iF7Ny8we9GLM6A",
//     department: "Finance",
//     role: "Sr. Analyst",
//     jobLevel: "Mid-level",
//     orgUnit: "Corporate Finance",
//     division: "Corporate",
//     doj: "2020-01-15",
//     location: "Gurgaon",
//     assessment: "Done",
//     projectScore: 85,
//     perfRating: 4.2,
//     oaapScore: 88,
//     technicalAssessmentScore: 83,
//     cognitiveAptitudeScore: 90,
//     recentProjectRating: 4.0,
//     deliverySpeed: 4.2,
//     employmentType: "Full-Time Permanent",
//     currentCompensationBand: "Band L3-B",
//     adjustedOaapScore: 8.9,
//     key: false,
//     potential: "High",
//     readiness: "1-2 Years",
//     readinessPct: 60,
//     tag: null,
//   },
//   {
//     id: "PID-6101",
//     name: "Ananya Gupta",
//     avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuAqfXqTC7-l11sZuITewKUM4h1zQ6B6guar2pUdcGXwWrk0NUNpzVAKj2uOTiSSlh8JGukiRoJlTYH8D1DN1DWOF6eWMLsaN0XMLvhI7X8LbFd-L8j_DoCof77a2HVKUq7tKkJqryeAonr040F7ms_6Gtot16PwWLVlBhRPH--g2Nwqqy2kTy3GaL4GNyv5aT5DlQ8uwNyFJLycVePAm9otl0pBVVj9NOYnDu16DOvrv6V5RfiGEvOIoOZrpF4HkKqiYjrdhX0i-u0",
//     department: "Pidilite Labs",
//     role: "Senior Data Scientist",
//     jobLevel: "Senior",
//     orgUnit: "AI Division",
//     division: "Consumer",
//     doj: "2016-09-30",
//     location: "Mumbai",
//     assessment: "Done",
//     projectScore: 91,
//     perfRating: 4.7,
//     oaapScore: 94,
//     technicalAssessmentScore: 90,
//     cognitiveAptitudeScore: 91,
//     recentProjectRating: 4.5,
//     deliverySpeed: 4.6,
//     employmentType: "Full-Time Permanent",
//     currentCompensationBand: "Band L4-A",
//     adjustedOaapScore: 9.5,
//     key: true,
//     potential: "High",
//     readiness: "Ready Now",
//     readinessPct: 100,
//     tag: "Top Performer",
//   },
//   {
//     id: "PID-6102",
//     name: "Rahul Verma",
//     avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuADHM0Ox9V9ZrvzFd0j7l4SWDvSBwD1rs7zVYWXxadoHJGaqGvNdjOgMMo8NOTlsV-0piifxEgjklD4vgh0ZCACxBVmbEAtDKRV43y7NXbtVTeVsB_FcZ_Ip5H1VE6ze53hnNTdfoTwlbXECOhVsnL4Fe5nyWp_ETTzaBTMTqwSPYz3hymqewVasIc5X4KkI24iDZhugzwklVoQx_alQ-2wdIKlksfbuv9DsmhsGGQ-WknFYyDfa_FBuXimMMa5Pi3VG61XMHeokbs",
//     department: "Sales",
//     role: "Regional Sales Manager",
//     jobLevel: "Manager",
//     orgUnit: "Sales - North Zone",
//     division: "Commercial",
//     doj: "2021-02-20",
//     location: "Delhi",
//     assessment: "Done",
//     projectScore: 89,
//     perfRating: 4.4,
//     oaapScore: 90,
//     technicalAssessmentScore: 87,
//     cognitiveAptitudeScore: 88,
//     recentProjectRating: 4.6,
//     deliverySpeed: 4.3,
//     employmentType: "Full-Time Permanent",
//     currentCompensationBand: "Band L3-A",
//     adjustedOaapScore: 9.3,
//     key: true,
//     potential: "High",
//     readiness: "1-2 Years",
//     readinessPct: 60,
//     tag: "Future Leader",
//   },
//   {
//     id: "PID-6103",
//     name: "Sarah Chen",
//     avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDxPWvtIF7kDnHPOMLfvLqtwodc0vnP0sK5YKSMATwso7adCZGFfOQl_-WSxD7xjP1kJsS-8EmET3bqIRJz88jfpmJJn-kjSFjkijW5EjvWVCIhvRxAH_M1mol3dcugeYOJobvOk2F0imOHE3uZHngId9zptWC4JPWSYhdOthl4Ic94bNiFzhbUufIGK57OTp8buMk4s2OS-7x6Sf_xt0Afbto0HfzEsTDC9NxCwD3H6bU7oTstxv3JRv9UzBjWa8IkeCxqBEJq_g4",
//     department: "Digital Innovation",
//     role: "Product Manager",
//     jobLevel: "Mid-level",
//     orgUnit: "Digital Products",
//     division: "Digital",
//     doj: "2020-07-11",
//     location: "Bangalore",
//     assessment: "Done",
//     projectScore: 82,
//     perfRating: 4.1,
//     oaapScore: 86,
//     technicalAssessmentScore: 80,
//     cognitiveAptitudeScore: 85,
//     recentProjectRating: 4.2,
//     deliverySpeed: 4.0,
//     employmentType: "Full-Time Permanent",
//     currentCompensationBand: "Band L2-A",
//     adjustedOaapScore: 8.7,
//     key: false,
//     potential: "High",
//     readiness: "3-5 Years",
//     readinessPct: 30,
//     tag: null,
//   },
//   {
//     id: "PID-6104",
//     name: "Priya Sharma",
//     avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuDE_XtWsvQzbYYnOIDTOydhutdII69snTbKn_EragK4IC_GiUEmfv37l0_nPMBQ3gxR4uPGPC-_yNbIYZbyosB5GjNw9KgfFrQbJoQSL5yVTi93T09hfXLwt66hdUyY6ck_WRupToYmkdcF0pBtqqsKH5xiipjZbuvp_86_DNSeq7udF5x_n1oKgqgrxovVeCsHRBu-zFYGFWCwe1LLMTgK4Q2oQ8sVsDLpWXMEx0-AL87aL-GX4vNFfihcUjKrmmnqKfIKVAg4SpM",
//     department: "People Operations",
//     role: "HR Business Partner",
//     jobLevel: "Mid-level",
//     orgUnit: "HR - Corporate",
//     division: "Corporate",
//     doj: "2015-05-22",
//     location: "Mumbai",
//     assessment: "Done",
//     projectScore: 90,
//     perfRating: 4.6,
//     oaapScore: 91,
//     technicalAssessmentScore: 85,
//     cognitiveAptitudeScore: 88,
//     recentProjectRating: 4.4,
//     deliverySpeed: 4.5,
//     employmentType: "Full-Time Permanent",
//     currentCompensationBand: "Band L3-A",
//     adjustedOaapScore: 9.0,
//     key: true,
//     potential: "High",
//     readiness: "Ready Now",
//     readinessPct: 100,
//     tag: "Specialist",
//   },
//   {
//     id: "PID-6105",
//     name: "Dev Kumar",
//     avatar: "https://lh3.googleusercontent.com/aida-public/AB6AXuBEdEMTJT-NpxQh4AQg3B3flsIzqlnjkjOgJtsfm0RxzHuK1XUc-NlS97DOv-z-sqZnRF2ZNBu7T3uC58c9yHVAgFtXrRnHqUh007LOqD77BHp-L46E0k_6lhA7Q4B0JHtTRvv2GYNg-8LzOdj3zgner1CRXQRwKIGYUKGjLzxQDAObMgyglg7TajVmmcTbRhBaqwlPtAEMe-SI-FEshPRvbq-Moz4YmBgG7xVsfgVUOUbfhkMMPYKNXvIa8aGjSJJrcNH3SGFBCss",
//     department: "Logistics",
//     role: "Supply Chain Analyst",
//     jobLevel: "Junior",
//     orgUnit: "Supply Chain",
//     division: "Industrial",
//     doj: "2022-08-01",
//     location: "Chennai",
//     assessment: "Pending",
//     projectScore: 70,
//     perfRating: 3.7,
//     oaapScore: 75,
//     technicalAssessmentScore: 78,
//     cognitiveAptitudeScore: 80,
//     recentProjectRating: 3.9,
//     deliverySpeed: 4.0,
//     employmentType: "Full-Time Permanent",
//     currentCompensationBand: "Band L2-A",
//     adjustedOaapScore: 7.8,
//     key: false,
//     potential: "Medium",
//     readiness: "1-2 Years",
//     readinessPct: 60,
//     tag: null,
//   }
// ];